#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_GAUCHE 4
#define STATE_TOURNE_GAUCHE_EN_COURS 5
#define STATE_TOURNE_DROITE 6
#define STATE_TOURNE_DROITE_EN_COURS 7
#define STATE_TOURNE_SUR_PLACE_GAUCHE 8
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 9
#define STATE_TOURNE_SUR_PLACE_DROITE 10
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 11
#define STATE_ARRET 12
#define STATE_ARRET_EN_COURS 13
#define STATE_RECULE 14
#define STATE_RECULE_EN_COURS 15
#define STATE_AVANCE_LENTEMENT 16
#define STATE_AVANCE_LENTEMENT_EN_COURS 17
#define STATE_TOURNE_LENTEMENT_DROITE 18
#define STATE_TOURNE_LENTEMENT_DROITE_EN_COURS 19
#define STATE_TOURNE_LENTEMENT_GAUCHE 20
#define STATE_TOURNE_LENTEMENT_GAUCHE_EN_COURS 21
#define STATE_JACQUES 100

#define PAS_D_OBSTACLE 0
#define OBSTACLE_A_GAUCHE 1
#define OBSTACLE_A_DROITE 2
#define OBSTACLE_EN_FACE 3
#define OBSTACLE_EN_FACE_DROIT 4
#define OBSTACLE_EN_FACE_GAUCHE 5
#define PROBLEME_FACE 6
#define OBSTACLE_X_GAUCHE 7
#define OBSTACLE_X_DROIT 8

#define FCY 40000000

void OperatingSystemLoop(void);
void SetNextRobotStateInAutomaticMode(void);
void SetRobotState(unsigned char state);
void SetRobotAutoControlState(unsigned char autoControlState);
void UartUpdateState (void);

#ifndef MAIN_H
#define	MAIN_H

#ifdef	__cplusplus
extern "C" {
#endif




#ifdef	__cplusplus
}
#endif

#endif	/* MAIN_H */

